### ISSUE TITLE
Publish 2.0.0 to npm registry

### ISSUE THREAD

**Issue by martincostello** [aspnet-contrib/generator-aspnet-oauth#18]
The [2.0.0](https://github.com/aspnet-contrib/generator-aspnet-oauth/releases/tag/2.0.0) release needs pushing to [npm](https://www.npmjs.com/package/generator-aspnet-oauth) so users can install a more updated version of the Yeoman generator.

I don't have permission to do this, but @PinpointTownes does 😉

**Comment by kevinchalet** [comment]
> I don't have permission to do this

What's your npm handle?

FWIW, I'm getting a stupid error ATM (most likely due to the special char/space in my Windows account name)

![image](https://user-images.githubusercontent.com/6998306/59212577-1c32aa00-8bb3-11e9-8c08-bc06fba2782e.png)

I'll take a closer look when I have a minute 😄

**Comment by martincostello** [comment]
I'm the rather originally named [martincostello](https://www.npmjs.com/~martincostello) 🤣

**Comment by kevinchalet** [comment]
You should now have write access granted. Lemme know if there's something I didn't do right 😄

**Comment by martincostello** [comment]
I _think_ I have access now as I can see this under my profile:

![image](https://user-images.githubusercontent.com/1439341/59215784-096ba580-8bb2-11e9-8a26-adc6a9261a74.png)

I'll see if I can publish the release later on today - thanks!

**Comment by martincostello** [comment]
Done: https://www.npmjs.com/package/generator-aspnet-oauth/v/2.0.0
